"""add_canonical_fields_to_grocery_list_items

Revision ID: 013a6556c321
Revises: 784c2322c745
Create Date: 2025-12-08 17:01:38.860718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013a6556c321'
down_revision: Union[str, Sequence[str], None] = '784c2322c745'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_list_items', sa.Column('canonical_quantity_needed', sa.Numeric(precision=10, scale=3), nullable=True, comment='Quantity needed in canonical unit (after pantry subtraction)'))
    op.add_column('grocery_list_items', sa.Column('canonical_unit', sa.String(length=16), nullable=True, comment='Canonical unit code (g, ml, count)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grocery_list_items', 'canonical_unit')
    op.drop_column('grocery_list_items', 'canonical_quantity_needed')
    # ### end Alembic commands ###
