"""add_performance_indexes

Revision ID: 1f5f699c2f99
Revises: 9d8175113336
Create Date: 2025-12-01 22:32:46.266108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5f699c2f99'
down_revision: Union[str, Sequence[str], None] = '9d8175113336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_msr_family_status_created', 'meal_share_requests', ['family_id', 'status', 'created_at'], unique=False)
    op.create_index('idx_msr_recipient_status', 'meal_share_requests', ['recipient_user_id', 'status'], unique=False)
    op.create_index('idx_msr_sender_created', 'meal_share_requests', ['sender_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_created_at'), 'meal_share_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_family_id'), 'meal_share_requests', ['family_id'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_meal_id'), 'meal_share_requests', ['meal_id'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_recipient_user_id'), 'meal_share_requests', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_sender_user_id'), 'meal_share_requests', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_status'), 'meal_share_requests', ['status'], unique=False)
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.create_index('idx_notif_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_notif_user_read_created', 'notifications', ['user_id', 'is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index('idx_pantry_family_expires', 'pantry_items', ['family_id', 'expires_at'], unique=False)
    op.create_index('idx_pantry_owner_expires', 'pantry_items', ['owner_user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_pantry_items_expires_at'), 'pantry_items', ['expires_at'], unique=False)
    op.create_index(op.f('ix_pantry_items_family_id'), 'pantry_items', ['family_id'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_tier'), 'users', ['tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tier'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_pantry_items_family_id'), table_name='pantry_items')
    op.drop_index(op.f('ix_pantry_items_expires_at'), table_name='pantry_items')
    op.drop_index('idx_pantry_owner_expires', table_name='pantry_items')
    op.drop_index('idx_pantry_family_expires', table_name='pantry_items')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index('idx_notif_user_read_created', table_name='notifications')
    op.drop_index('idx_notif_user_created', table_name='notifications')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_meal_share_requests_status'), table_name='meal_share_requests')
    op.drop_index(op.f('ix_meal_share_requests_sender_user_id'), table_name='meal_share_requests')
    op.drop_index(op.f('ix_meal_share_requests_recipient_user_id'), table_name='meal_share_requests')
    op.drop_index(op.f('ix_meal_share_requests_meal_id'), table_name='meal_share_requests')
    op.drop_index(op.f('ix_meal_share_requests_family_id'), table_name='meal_share_requests')
    op.drop_index(op.f('ix_meal_share_requests_created_at'), table_name='meal_share_requests')
    op.drop_index('idx_msr_sender_created', table_name='meal_share_requests')
    op.drop_index('idx_msr_recipient_status', table_name='meal_share_requests')
    op.drop_index('idx_msr_family_status_created', table_name='meal_share_requests')
    # ### end Alembic commands ###
