"""add_created_by_and_updated_at_to_grocery_lists

Revision ID: 4b70ac002467
Revises: 54f16841f909
Create Date: 2025-12-07 12:00:42.697166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b70ac002467'
down_revision: Union[str, Sequence[str], None] = '54f16841f909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grocery_lists', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('grocery_lists', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))

    # Backfill: For personal lists, set created_by_user_id = owner_user_id
    op.execute("""
        UPDATE grocery_lists
        SET created_by_user_id = owner_user_id
        WHERE owner_user_id IS NOT NULL
    """)

    # Conditionally drop index if it exists (may not exist in all environments)
    conn = op.get_bind()
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = 'idx_grocery_list_meal_plan'"
    ))
    if result.fetchone():
        op.drop_index('idx_grocery_list_meal_plan', table_name='grocery_lists')

    op.create_index(op.f('ix_grocery_lists_created_by_user_id'), 'grocery_lists', ['created_by_user_id'], unique=False)

    # Conditionally create indexes if they don't exist
    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = 'ix_grocery_lists_family_id'"
    ))
    if not result.fetchone():
        op.create_index(op.f('ix_grocery_lists_family_id'), 'grocery_lists', ['family_id'], unique=False)

    result = conn.execute(sa.text(
        "SELECT 1 FROM pg_indexes WHERE indexname = 'ix_grocery_lists_owner_user_id'"
    ))
    if not result.fetchone():
        op.create_index(op.f('ix_grocery_lists_owner_user_id'), 'grocery_lists', ['owner_user_id'], unique=False)

    op.create_foreign_key('fk_grocery_lists_created_by_user', 'grocery_lists', 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_grocery_lists_created_by_user', 'grocery_lists', type_='foreignkey')
    op.drop_index(op.f('ix_grocery_lists_created_by_user_id'), table_name='grocery_lists')
    op.create_index('idx_grocery_list_meal_plan', 'grocery_lists', ['meal_plan_id'], unique=False)
    op.drop_column('grocery_lists', 'updated_at')
    op.drop_column('grocery_lists', 'created_by_user_id')
    # ### end Alembic commands ###
