"""add is_internal column to chat_messages

Revision ID: 573d0f0f08cd
Revises: 6c8fbe1aca82
Create Date: 2025-12-12 22:57:57.659304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573d0f0f08cd'
down_revision: Union[str, Sequence[str], None] = '6c8fbe1aca82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('is_internal', sa.Integer(), nullable=False, server_default='0'))
    op.drop_index(op.f('idx_grocery_list_items_source_meal_plan'), table_name='grocery_list_items')
    op.create_index(op.f('ix_grocery_list_items_source_meal_plan_id'), 'grocery_list_items', ['source_meal_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_grocery_list_items_source_meal_plan_id'), table_name='grocery_list_items')
    op.create_index(op.f('idx_grocery_list_items_source_meal_plan'), 'grocery_list_items', ['source_meal_plan_id'], unique=False)
    op.drop_column('chat_messages', 'is_internal')
    # ### end Alembic commands ###
