"""add_unit_normalization_fields

Revision ID: 784c2322c745
Revises: 4b70ac002467
Create Date: 2025-12-08 16:51:16.284853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '784c2322c745'
down_revision: Union[str, Sequence[str], None] = '4b70ac002467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the ENUM type first
    canonical_unit_type_enum = sa.Enum('weight', 'volume', 'count', name='canonical_unit_type_enum')
    canonical_unit_type_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('ingredients', sa.Column('canonical_unit_type', sa.Enum('weight', 'volume', 'count', name='canonical_unit_type_enum', create_constraint=True), nullable=True, comment='Type of canonical unit: weight, volume, or count'))
    op.add_column('ingredients', sa.Column('canonical_unit', sa.Text(), nullable=True, comment='Canonical unit code: g, ml, count, etc.'))
    op.add_column('ingredients', sa.Column('avg_weight_per_unit_g', sa.Float(), nullable=True, comment='Average weight in grams for one unit (e.g., one egg = 50g)'))
    op.add_column('ingredients', sa.Column('density_g_per_ml', sa.Float(), nullable=True, comment='Density in grams per milliliter for volume-to-weight conversion'))
    op.add_column('ingredients', sa.Column('pieces_per_package', sa.Integer(), nullable=True, comment='Number of pieces in a standard package'))
    op.add_column('pantry_items', sa.Column('canonical_quantity', sa.Numeric(precision=10, scale=3), nullable=True, comment="Quantity normalized to ingredient's canonical unit"))
    op.add_column('pantry_items', sa.Column('canonical_unit', sa.String(length=16), nullable=True, comment='Canonical unit code (g, ml, count)'))
    op.add_column('recipe_ingredients', sa.Column('canonical_quantity', sa.Numeric(precision=10, scale=3), nullable=True, comment="Quantity normalized to ingredient's canonical unit"))
    op.add_column('recipe_ingredients', sa.Column('canonical_unit', sa.String(length=16), nullable=True, comment='Canonical unit code (g, ml, count)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_ingredients', 'canonical_unit')
    op.drop_column('recipe_ingredients', 'canonical_quantity')
    op.drop_column('pantry_items', 'canonical_unit')
    op.drop_column('pantry_items', 'canonical_quantity')
    op.drop_column('ingredients', 'pieces_per_package')
    op.drop_column('ingredients', 'density_g_per_ml')
    op.drop_column('ingredients', 'avg_weight_per_unit_g')
    op.drop_column('ingredients', 'canonical_unit')
    op.drop_column('ingredients', 'canonical_unit_type')

    # Drop the enum type
    op.execute("DROP TYPE IF EXISTS canonical_unit_type_enum")
    # ### end Alembic commands ###
