"""create missing tables

Revision ID: cc165de93a4b
Revises: b7d4f0a2c1e9
Create Date: 2025-11-06 04:57:09.467340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc165de93a4b'
down_revision: Union[str, Sequence[str], None] = 'b7d4f0a2c1e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_share_requests_recipient_user_id'), table_name='meal_share_requests')
    op.drop_index(op.f('ix_meal_share_requests_sender_user_id'), table_name='meal_share_requests')
    op.drop_index(op.f('ix_meal_share_requests_status'), table_name='meal_share_requests')
    op.drop_table('meal_share_requests')
    op.drop_column('meals', 'shared_with_family')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('shared_with_family', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_table('meal_share_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'declined', name='meal_share_request_status'), server_default=sa.text("'pending'::meal_share_request_status"), autoincrement=False, nullable=False),
    sa.Column('message', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('meal_share_requests_family_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('meal_share_requests_meal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('meal_share_requests_recipient_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('meal_share_requests_sender_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_share_requests_pkey'))
    )
    op.create_index(op.f('ix_meal_share_requests_status'), 'meal_share_requests', ['status'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_sender_user_id'), 'meal_share_requests', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_meal_share_requests_recipient_user_id'), 'meal_share_requests', ['recipient_user_id'], unique=False)
    # ### end Alembic commands ###
