"""add calories field to users

Revision ID: dd47083e6273
Revises: 8167ab6fda78
Create Date: 2025-11-27 22:24:58.517207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dd47083e6273'
down_revision: Union[str, Sequence[str], None] = '8167ab6fda78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meal_share_requests')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_table('notifications')
    op.add_column('users', sa.Column('calories', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calories')
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('related_meal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('related_family_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('related_share_request_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['related_family_id'], ['families.id'], name=op.f('notifications_related_family_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_meal_id'], ['meals.id'], name=op.f('notifications_related_meal_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], name=op.f('notifications_related_user_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id'], unique=False, postgresql_where='(is_read = false)')
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_table('meal_share_requests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('meal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('sender_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('recipient_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('family_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'declined', name='meal_share_request_status'), server_default=sa.text("'pending'::meal_share_request_status"), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('responded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('accepted_meal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['accepted_meal_id'], ['meals.id'], name=op.f('fk_meal_share_requests_accepted_meal_id'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], name=op.f('meal_share_requests_family_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('meal_share_requests_meal_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], name=op.f('meal_share_requests_recipient_user_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('meal_share_requests_sender_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('meal_share_requests_pkey'))
    )
    # ### end Alembic commands ###
