"""Add image_url to pantry_items

Revision ID: e7297cd4ed75
Revises: 16cde467c8f3
Create Date: 2025-10-31 15:54:39.169505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7297cd4ed75'
down_revision: Union[str, Sequence[str], None] = '16cde467c8f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pantry_items', sa.Column('image_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pantry_items', 'image_url')
    # ### end Alembic commands ###
